<?php

namespace AppBundle\Repository;

/**
 * AnnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
